### ISSUE TITLE
Read Failed, socket might closed

### ISSUE THREAD

**Issue by aakashsharmaindore** [halilkabaca/NovarumBluetooth#5]
hey ,
i am facing a error when i m connecting device to other, alert shows 
"read failed socket might closed or timeout read ret : -1", i cross checked it more devices its not working, 

//****************************_Error**_******
[ERROR] :  System: Uncaught exception thrown by finalizer
[ERROR] :  System: java.io.IOException: socket not created
[ERROR] :  System:  at android.net.LocalSocketImpl.shutdownInput(LocalSocketImpl.java:396)
[ERROR] :  System:  at android.net.LocalSocket.shutdownInput(LocalSocket.java:206)
[ERROR] :  System:  at android.bluetooth.BluetoothSocket.close(BluetoothSocket.java:464)
[ERROR] :  System:  at android.bluetooth.BluetoothSocket.finalize(BluetoothSocket.java:221)
[ERROR] :  System:  at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
[ERROR] :  System:  at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
[ERROR] :  System:  at java.lang.Thread.run(Thread.java:818)

//************************************************************
can u please.
i am waiting for your response

**Comment by halilkabaca** [comment]
Hello. I have never tried a connection between two android phones. This module is only for connecting android phones to some devices. I think it fails to create the socket. Do you have any bluetooth enabled device you can test with? I am curious if you can establish the connection that way. 

Let me know please.

Regards
Halil

**Comment by aakashsharmaindore** [comment]
Yes, I tried it at my end, connecting two android devices, but it fails again, it says, "Socket connection failed". Any idea to overcome this .. also If you have some useful links or module please revert me with that .

Regards, 
Aakash
